// Code generated by MockGen. DO NOT EDIT.
// Source: repository/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=repository/interfaces.go -destination=repository/mock_repository.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	reflect "reflect"

	models "github.com/arxdsilva/hackathon/models"
	gomock "go.uber.org/mock/gomock"
)

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CompanyAllowedDomainFindAll mocks base method.
func (m *MockRepositoryInterface) CompanyAllowedDomainFindAll() (*models.CompanyAllowedDomains, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompanyAllowedDomainFindAll")
	ret0, _ := ret[0].(*models.CompanyAllowedDomains)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompanyAllowedDomainFindAll indicates an expected call of CompanyAllowedDomainFindAll.
func (mr *MockRepositoryInterfaceMockRecorder) CompanyAllowedDomainFindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompanyAllowedDomainFindAll", reflect.TypeOf((*MockRepositoryInterface)(nil).CompanyAllowedDomainFindAll))
}

// CompanyAllowedDomainFindAllActive mocks base method.
func (m *MockRepositoryInterface) CompanyAllowedDomainFindAllActive() (*models.CompanyAllowedDomains, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompanyAllowedDomainFindAllActive")
	ret0, _ := ret[0].(*models.CompanyAllowedDomains)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompanyAllowedDomainFindAllActive indicates an expected call of CompanyAllowedDomainFindAllActive.
func (mr *MockRepositoryInterfaceMockRecorder) CompanyAllowedDomainFindAllActive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompanyAllowedDomainFindAllActive", reflect.TypeOf((*MockRepositoryInterface)(nil).CompanyAllowedDomainFindAllActive))
}

// CompanyAllowedDomainIsDomainAllowed mocks base method.
func (m *MockRepositoryInterface) CompanyAllowedDomainIsDomainAllowed(domain string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompanyAllowedDomainIsDomainAllowed", domain)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompanyAllowedDomainIsDomainAllowed indicates an expected call of CompanyAllowedDomainIsDomainAllowed.
func (mr *MockRepositoryInterfaceMockRecorder) CompanyAllowedDomainIsDomainAllowed(domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompanyAllowedDomainIsDomainAllowed", reflect.TypeOf((*MockRepositoryInterface)(nil).CompanyAllowedDomainIsDomainAllowed), domain)
}

// FileFindAll mocks base method.
func (m *MockRepositoryInterface) FileFindAll() (*models.Files, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileFindAll")
	ret0, _ := ret[0].(*models.Files)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FileFindAll indicates an expected call of FileFindAll.
func (mr *MockRepositoryInterfaceMockRecorder) FileFindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileFindAll", reflect.TypeOf((*MockRepositoryInterface)(nil).FileFindAll))
}

// FileFindAllHackathons mocks base method.
func (m *MockRepositoryInterface) FileFindAllHackathons() (*models.Hackathons, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileFindAllHackathons")
	ret0, _ := ret[0].(*models.Hackathons)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FileFindAllHackathons indicates an expected call of FileFindAllHackathons.
func (mr *MockRepositoryInterfaceMockRecorder) FileFindAllHackathons() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileFindAllHackathons", reflect.TypeOf((*MockRepositoryInterface)(nil).FileFindAllHackathons))
}

// FileFindAllProjects mocks base method.
func (m *MockRepositoryInterface) FileFindAllProjects() (*models.Projects, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileFindAllProjects")
	ret0, _ := ret[0].(*models.Projects)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FileFindAllProjects indicates an expected call of FileFindAllProjects.
func (mr *MockRepositoryInterfaceMockRecorder) FileFindAllProjects() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileFindAllProjects", reflect.TypeOf((*MockRepositoryInterface)(nil).FileFindAllProjects))
}

// FileFindByID mocks base method.
func (m *MockRepositoryInterface) FileFindByID(id any) (*models.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileFindByID", id)
	ret0, _ := ret[0].(*models.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FileFindByID indicates an expected call of FileFindByID.
func (mr *MockRepositoryInterfaceMockRecorder) FileFindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileFindByID", reflect.TypeOf((*MockRepositoryInterface)(nil).FileFindByID), id)
}

// HackathonCount mocks base method.
func (m *MockRepositoryInterface) HackathonCount() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HackathonCount")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HackathonCount indicates an expected call of HackathonCount.
func (mr *MockRepositoryInterfaceMockRecorder) HackathonCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HackathonCount", reflect.TypeOf((*MockRepositoryInterface)(nil).HackathonCount))
}

// HackathonFindByID mocks base method.
func (m *MockRepositoryInterface) HackathonFindByID(id any) (*models.Hackathon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HackathonFindByID", id)
	ret0, _ := ret[0].(*models.Hackathon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HackathonFindByID indicates an expected call of HackathonFindByID.
func (mr *MockRepositoryInterfaceMockRecorder) HackathonFindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HackathonFindByID", reflect.TypeOf((*MockRepositoryInterface)(nil).HackathonFindByID), id)
}

// HackathonFindByOwnerID mocks base method.
func (m *MockRepositoryInterface) HackathonFindByOwnerID(ownerID any) (*models.Hackathons, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HackathonFindByOwnerID", ownerID)
	ret0, _ := ret[0].(*models.Hackathons)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HackathonFindByOwnerID indicates an expected call of HackathonFindByOwnerID.
func (mr *MockRepositoryInterfaceMockRecorder) HackathonFindByOwnerID(ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HackathonFindByOwnerID", reflect.TypeOf((*MockRepositoryInterface)(nil).HackathonFindByOwnerID), ownerID)
}

// HackathonGetActiveHackathonIDs mocks base method.
func (m *MockRepositoryInterface) HackathonGetActiveHackathonIDs() ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HackathonGetActiveHackathonIDs")
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HackathonGetActiveHackathonIDs indicates an expected call of HackathonGetActiveHackathonIDs.
func (mr *MockRepositoryInterfaceMockRecorder) HackathonGetActiveHackathonIDs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HackathonGetActiveHackathonIDs", reflect.TypeOf((*MockRepositoryInterface)(nil).HackathonGetActiveHackathonIDs))
}

// HackathonGetActiveWithSchedule mocks base method.
func (m *MockRepositoryInterface) HackathonGetActiveWithSchedule() (*models.Hackathons, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HackathonGetActiveWithSchedule")
	ret0, _ := ret[0].(*models.Hackathons)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HackathonGetActiveWithSchedule indicates an expected call of HackathonGetActiveWithSchedule.
func (mr *MockRepositoryInterfaceMockRecorder) HackathonGetActiveWithSchedule() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HackathonGetActiveWithSchedule", reflect.TypeOf((*MockRepositoryInterface)(nil).HackathonGetActiveWithSchedule))
}

// HackathonGetRecent mocks base method.
func (m *MockRepositoryInterface) HackathonGetRecent(limit int) (*models.Hackathons, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HackathonGetRecent", limit)
	ret0, _ := ret[0].(*models.Hackathons)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HackathonGetRecent indicates an expected call of HackathonGetRecent.
func (mr *MockRepositoryInterfaceMockRecorder) HackathonGetRecent(limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HackathonGetRecent", reflect.TypeOf((*MockRepositoryInterface)(nil).HackathonGetRecent), limit)
}

// ProjectCount mocks base method.
func (m *MockRepositoryInterface) ProjectCount() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectCount")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProjectCount indicates an expected call of ProjectCount.
func (mr *MockRepositoryInterfaceMockRecorder) ProjectCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectCount", reflect.TypeOf((*MockRepositoryInterface)(nil).ProjectCount))
}

// ProjectCountActive mocks base method.
func (m *MockRepositoryInterface) ProjectCountActive() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectCountActive")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProjectCountActive indicates an expected call of ProjectCountActive.
func (mr *MockRepositoryInterfaceMockRecorder) ProjectCountActive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectCountActive", reflect.TypeOf((*MockRepositoryInterface)(nil).ProjectCountActive))
}

// ProjectCountMembershipsByProjectID mocks base method.
func (m *MockRepositoryInterface) ProjectCountMembershipsByProjectID(projectID any) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectCountMembershipsByProjectID", projectID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProjectCountMembershipsByProjectID indicates an expected call of ProjectCountMembershipsByProjectID.
func (mr *MockRepositoryInterfaceMockRecorder) ProjectCountMembershipsByProjectID(projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectCountMembershipsByProjectID", reflect.TypeOf((*MockRepositoryInterface)(nil).ProjectCountMembershipsByProjectID), projectID)
}

// ProjectCountPresenting mocks base method.
func (m *MockRepositoryInterface) ProjectCountPresenting() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectCountPresenting")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProjectCountPresenting indicates an expected call of ProjectCountPresenting.
func (mr *MockRepositoryInterfaceMockRecorder) ProjectCountPresenting() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectCountPresenting", reflect.TypeOf((*MockRepositoryInterface)(nil).ProjectCountPresenting))
}

// ProjectFindByHackathonID mocks base method.
func (m *MockRepositoryInterface) ProjectFindByHackathonID(hackathonID any) (*models.Projects, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectFindByHackathonID", hackathonID)
	ret0, _ := ret[0].(*models.Projects)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProjectFindByHackathonID indicates an expected call of ProjectFindByHackathonID.
func (mr *MockRepositoryInterfaceMockRecorder) ProjectFindByHackathonID(hackathonID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectFindByHackathonID", reflect.TypeOf((*MockRepositoryInterface)(nil).ProjectFindByHackathonID), hackathonID)
}

// ProjectFindByID mocks base method.
func (m *MockRepositoryInterface) ProjectFindByID(id any) (*models.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectFindByID", id)
	ret0, _ := ret[0].(*models.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProjectFindByID indicates an expected call of ProjectFindByID.
func (mr *MockRepositoryInterfaceMockRecorder) ProjectFindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectFindByID", reflect.TypeOf((*MockRepositoryInterface)(nil).ProjectFindByID), id)
}

// ProjectFindByUserID mocks base method.
func (m *MockRepositoryInterface) ProjectFindByUserID(userID any) (*models.Projects, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectFindByUserID", userID)
	ret0, _ := ret[0].(*models.Projects)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProjectFindByUserID indicates an expected call of ProjectFindByUserID.
func (mr *MockRepositoryInterfaceMockRecorder) ProjectFindByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectFindByUserID", reflect.TypeOf((*MockRepositoryInterface)(nil).ProjectFindByUserID), userID)
}

// ProjectFindByUserIDWithHackathon mocks base method.
func (m *MockRepositoryInterface) ProjectFindByUserIDWithHackathon(userID any) (*models.Projects, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectFindByUserIDWithHackathon", userID)
	ret0, _ := ret[0].(*models.Projects)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProjectFindByUserIDWithHackathon indicates an expected call of ProjectFindByUserIDWithHackathon.
func (mr *MockRepositoryInterfaceMockRecorder) ProjectFindByUserIDWithHackathon(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectFindByUserIDWithHackathon", reflect.TypeOf((*MockRepositoryInterface)(nil).ProjectFindByUserIDWithHackathon), userID)
}

// ProjectFindPresentingByHackathonID mocks base method.
func (m *MockRepositoryInterface) ProjectFindPresentingByHackathonID(hackathonID any) (*models.Projects, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectFindPresentingByHackathonID", hackathonID)
	ret0, _ := ret[0].(*models.Projects)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProjectFindPresentingByHackathonID indicates an expected call of ProjectFindPresentingByHackathonID.
func (mr *MockRepositoryInterfaceMockRecorder) ProjectFindPresentingByHackathonID(hackathonID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectFindPresentingByHackathonID", reflect.TypeOf((*MockRepositoryInterface)(nil).ProjectFindPresentingByHackathonID), hackathonID)
}

// ProjectFindPresentingFromActiveHackathons mocks base method.
func (m *MockRepositoryInterface) ProjectFindPresentingFromActiveHackathons() (*models.Projects, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectFindPresentingFromActiveHackathons")
	ret0, _ := ret[0].(*models.Projects)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProjectFindPresentingFromActiveHackathons indicates an expected call of ProjectFindPresentingFromActiveHackathons.
func (mr *MockRepositoryInterfaceMockRecorder) ProjectFindPresentingFromActiveHackathons() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectFindPresentingFromActiveHackathons", reflect.TypeOf((*MockRepositoryInterface)(nil).ProjectFindPresentingFromActiveHackathons))
}

// ProjectGetFilesByProjectID mocks base method.
func (m *MockRepositoryInterface) ProjectGetFilesByProjectID(projectID any) (*models.Files, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectGetFilesByProjectID", projectID)
	ret0, _ := ret[0].(*models.Files)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProjectGetFilesByProjectID indicates an expected call of ProjectGetFilesByProjectID.
func (mr *MockRepositoryInterfaceMockRecorder) ProjectGetFilesByProjectID(projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectGetFilesByProjectID", reflect.TypeOf((*MockRepositoryInterface)(nil).ProjectGetFilesByProjectID), projectID)
}

// ProjectGetMembershipsByProjectID mocks base method.
func (m *MockRepositoryInterface) ProjectGetMembershipsByProjectID(projectID any) (*models.ProjectMemberships, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectGetMembershipsByProjectID", projectID)
	ret0, _ := ret[0].(*models.ProjectMemberships)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProjectGetMembershipsByProjectID indicates an expected call of ProjectGetMembershipsByProjectID.
func (mr *MockRepositoryInterfaceMockRecorder) ProjectGetMembershipsByProjectID(projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectGetMembershipsByProjectID", reflect.TypeOf((*MockRepositoryInterface)(nil).ProjectGetMembershipsByProjectID), projectID)
}

// ProjectGetRecent mocks base method.
func (m *MockRepositoryInterface) ProjectGetRecent(limit int) (*models.Projects, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectGetRecent", limit)
	ret0, _ := ret[0].(*models.Projects)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProjectGetRecent indicates an expected call of ProjectGetRecent.
func (mr *MockRepositoryInterfaceMockRecorder) ProjectGetRecent(limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectGetRecent", reflect.TypeOf((*MockRepositoryInterface)(nil).ProjectGetRecent), limit)
}

// ProjectIsUserMemberOfProject mocks base method.
func (m *MockRepositoryInterface) ProjectIsUserMemberOfProject(projectID, userID any) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectIsUserMemberOfProject", projectID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProjectIsUserMemberOfProject indicates an expected call of ProjectIsUserMemberOfProject.
func (mr *MockRepositoryInterfaceMockRecorder) ProjectIsUserMemberOfProject(projectID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectIsUserMemberOfProject", reflect.TypeOf((*MockRepositoryInterface)(nil).ProjectIsUserMemberOfProject), projectID, userID)
}

// ProjectMembershipCountByProjectID mocks base method.
func (m *MockRepositoryInterface) ProjectMembershipCountByProjectID(projectID any) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectMembershipCountByProjectID", projectID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProjectMembershipCountByProjectID indicates an expected call of ProjectMembershipCountByProjectID.
func (mr *MockRepositoryInterfaceMockRecorder) ProjectMembershipCountByProjectID(projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectMembershipCountByProjectID", reflect.TypeOf((*MockRepositoryInterface)(nil).ProjectMembershipCountByProjectID), projectID)
}

// ProjectMembershipFindByProjectIDAndUserID mocks base method.
func (m *MockRepositoryInterface) ProjectMembershipFindByProjectIDAndUserID(projectID, userID any) (*models.ProjectMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectMembershipFindByProjectIDAndUserID", projectID, userID)
	ret0, _ := ret[0].(*models.ProjectMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProjectMembershipFindByProjectIDAndUserID indicates an expected call of ProjectMembershipFindByProjectIDAndUserID.
func (mr *MockRepositoryInterfaceMockRecorder) ProjectMembershipFindByProjectIDAndUserID(projectID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectMembershipFindByProjectIDAndUserID", reflect.TypeOf((*MockRepositoryInterface)(nil).ProjectMembershipFindByProjectIDAndUserID), projectID, userID)
}

// ProjectMembershipIsUserMember mocks base method.
func (m *MockRepositoryInterface) ProjectMembershipIsUserMember(projectID, userID any) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectMembershipIsUserMember", projectID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProjectMembershipIsUserMember indicates an expected call of ProjectMembershipIsUserMember.
func (mr *MockRepositoryInterfaceMockRecorder) ProjectMembershipIsUserMember(projectID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectMembershipIsUserMember", reflect.TypeOf((*MockRepositoryInterface)(nil).ProjectMembershipIsUserMember), projectID, userID)
}

// UserCount mocks base method.
func (m *MockRepositoryInterface) UserCount() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserCount")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserCount indicates an expected call of UserCount.
func (mr *MockRepositoryInterfaceMockRecorder) UserCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserCount", reflect.TypeOf((*MockRepositoryInterface)(nil).UserCount))
}

// UserFindByEmail mocks base method.
func (m *MockRepositoryInterface) UserFindByEmail(email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserFindByEmail", email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserFindByEmail indicates an expected call of UserFindByEmail.
func (mr *MockRepositoryInterfaceMockRecorder) UserFindByEmail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserFindByEmail", reflect.TypeOf((*MockRepositoryInterface)(nil).UserFindByEmail), email)
}

// UserFindByID mocks base method.
func (m *MockRepositoryInterface) UserFindByID(id any) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserFindByID", id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserFindByID indicates an expected call of UserFindByID.
func (mr *MockRepositoryInterfaceMockRecorder) UserFindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserFindByID", reflect.TypeOf((*MockRepositoryInterface)(nil).UserFindByID), id)
}

// UserFindByIDs mocks base method.
func (m *MockRepositoryInterface) UserFindByIDs(ids []any) (*models.Users, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserFindByIDs", ids)
	ret0, _ := ret[0].(*models.Users)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserFindByIDs indicates an expected call of UserFindByIDs.
func (mr *MockRepositoryInterfaceMockRecorder) UserFindByIDs(ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserFindByIDs", reflect.TypeOf((*MockRepositoryInterface)(nil).UserFindByIDs), ids)
}

// UserGetRecent mocks base method.
func (m *MockRepositoryInterface) UserGetRecent(limit int) (*models.Users, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserGetRecent", limit)
	ret0, _ := ret[0].(*models.Users)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserGetRecent indicates an expected call of UserGetRecent.
func (mr *MockRepositoryInterfaceMockRecorder) UserGetRecent(limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserGetRecent", reflect.TypeOf((*MockRepositoryInterface)(nil).UserGetRecent), limit)
}

// MockUserRepositoryInterface is a mock of UserRepositoryInterface interface.
type MockUserRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockUserRepositoryInterfaceMockRecorder is the mock recorder for MockUserRepositoryInterface.
type MockUserRepositoryInterfaceMockRecorder struct {
	mock *MockUserRepositoryInterface
}

// NewMockUserRepositoryInterface creates a new mock instance.
func NewMockUserRepositoryInterface(ctrl *gomock.Controller) *MockUserRepositoryInterface {
	mock := &MockUserRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepositoryInterface) EXPECT() *MockUserRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockUserRepositoryInterface) Count() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockUserRepositoryInterfaceMockRecorder) Count() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockUserRepositoryInterface)(nil).Count))
}

// FindByEmail mocks base method.
func (m *MockUserRepositoryInterface) FindByEmail(email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockUserRepositoryInterfaceMockRecorder) FindByEmail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockUserRepositoryInterface)(nil).FindByEmail), email)
}

// FindByID mocks base method.
func (m *MockUserRepositoryInterface) FindByID(id any) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockUserRepositoryInterfaceMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockUserRepositoryInterface)(nil).FindByID), id)
}

// FindByIDs mocks base method.
func (m *MockUserRepositoryInterface) FindByIDs(ids []any) (*models.Users, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDs", ids)
	ret0, _ := ret[0].(*models.Users)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDs indicates an expected call of FindByIDs.
func (mr *MockUserRepositoryInterfaceMockRecorder) FindByIDs(ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDs", reflect.TypeOf((*MockUserRepositoryInterface)(nil).FindByIDs), ids)
}

// GetRecent mocks base method.
func (m *MockUserRepositoryInterface) GetRecent(limit int) (*models.Users, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecent", limit)
	ret0, _ := ret[0].(*models.Users)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecent indicates an expected call of GetRecent.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetRecent(limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecent", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetRecent), limit)
}

// MockHackathonRepositoryInterface is a mock of HackathonRepositoryInterface interface.
type MockHackathonRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockHackathonRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockHackathonRepositoryInterfaceMockRecorder is the mock recorder for MockHackathonRepositoryInterface.
type MockHackathonRepositoryInterfaceMockRecorder struct {
	mock *MockHackathonRepositoryInterface
}

// NewMockHackathonRepositoryInterface creates a new mock instance.
func NewMockHackathonRepositoryInterface(ctrl *gomock.Controller) *MockHackathonRepositoryInterface {
	mock := &MockHackathonRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockHackathonRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHackathonRepositoryInterface) EXPECT() *MockHackathonRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockHackathonRepositoryInterface) Count() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockHackathonRepositoryInterfaceMockRecorder) Count() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockHackathonRepositoryInterface)(nil).Count))
}

// FindByID mocks base method.
func (m *MockHackathonRepositoryInterface) FindByID(id any) (*models.Hackathon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*models.Hackathon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockHackathonRepositoryInterfaceMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockHackathonRepositoryInterface)(nil).FindByID), id)
}

// FindByOwnerID mocks base method.
func (m *MockHackathonRepositoryInterface) FindByOwnerID(ownerID any) (*models.Hackathons, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOwnerID", ownerID)
	ret0, _ := ret[0].(*models.Hackathons)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByOwnerID indicates an expected call of FindByOwnerID.
func (mr *MockHackathonRepositoryInterfaceMockRecorder) FindByOwnerID(ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOwnerID", reflect.TypeOf((*MockHackathonRepositoryInterface)(nil).FindByOwnerID), ownerID)
}

// GetActiveHackathonIDs mocks base method.
func (m *MockHackathonRepositoryInterface) GetActiveHackathonIDs() ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveHackathonIDs")
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveHackathonIDs indicates an expected call of GetActiveHackathonIDs.
func (mr *MockHackathonRepositoryInterfaceMockRecorder) GetActiveHackathonIDs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveHackathonIDs", reflect.TypeOf((*MockHackathonRepositoryInterface)(nil).GetActiveHackathonIDs))
}

// GetActiveWithSchedule mocks base method.
func (m *MockHackathonRepositoryInterface) GetActiveWithSchedule() (*models.Hackathons, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveWithSchedule")
	ret0, _ := ret[0].(*models.Hackathons)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveWithSchedule indicates an expected call of GetActiveWithSchedule.
func (mr *MockHackathonRepositoryInterfaceMockRecorder) GetActiveWithSchedule() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveWithSchedule", reflect.TypeOf((*MockHackathonRepositoryInterface)(nil).GetActiveWithSchedule))
}

// GetRecent mocks base method.
func (m *MockHackathonRepositoryInterface) GetRecent(limit int) (*models.Hackathons, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecent", limit)
	ret0, _ := ret[0].(*models.Hackathons)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecent indicates an expected call of GetRecent.
func (mr *MockHackathonRepositoryInterfaceMockRecorder) GetRecent(limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecent", reflect.TypeOf((*MockHackathonRepositoryInterface)(nil).GetRecent), limit)
}

// MockProjectRepositoryInterface is a mock of ProjectRepositoryInterface interface.
type MockProjectRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockProjectRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockProjectRepositoryInterfaceMockRecorder is the mock recorder for MockProjectRepositoryInterface.
type MockProjectRepositoryInterfaceMockRecorder struct {
	mock *MockProjectRepositoryInterface
}

// NewMockProjectRepositoryInterface creates a new mock instance.
func NewMockProjectRepositoryInterface(ctrl *gomock.Controller) *MockProjectRepositoryInterface {
	mock := &MockProjectRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockProjectRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectRepositoryInterface) EXPECT() *MockProjectRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockProjectRepositoryInterface) Count() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockProjectRepositoryInterfaceMockRecorder) Count() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockProjectRepositoryInterface)(nil).Count))
}

// CountActive mocks base method.
func (m *MockProjectRepositoryInterface) CountActive() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActive")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActive indicates an expected call of CountActive.
func (mr *MockProjectRepositoryInterfaceMockRecorder) CountActive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActive", reflect.TypeOf((*MockProjectRepositoryInterface)(nil).CountActive))
}

// CountMembershipsByProjectID mocks base method.
func (m *MockProjectRepositoryInterface) CountMembershipsByProjectID(projectID any) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountMembershipsByProjectID", projectID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountMembershipsByProjectID indicates an expected call of CountMembershipsByProjectID.
func (mr *MockProjectRepositoryInterfaceMockRecorder) CountMembershipsByProjectID(projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountMembershipsByProjectID", reflect.TypeOf((*MockProjectRepositoryInterface)(nil).CountMembershipsByProjectID), projectID)
}

// CountPresenting mocks base method.
func (m *MockProjectRepositoryInterface) CountPresenting() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPresenting")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPresenting indicates an expected call of CountPresenting.
func (mr *MockProjectRepositoryInterfaceMockRecorder) CountPresenting() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPresenting", reflect.TypeOf((*MockProjectRepositoryInterface)(nil).CountPresenting))
}

// FindByHackathonID mocks base method.
func (m *MockProjectRepositoryInterface) FindByHackathonID(hackathonID any) (*models.Projects, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByHackathonID", hackathonID)
	ret0, _ := ret[0].(*models.Projects)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByHackathonID indicates an expected call of FindByHackathonID.
func (mr *MockProjectRepositoryInterfaceMockRecorder) FindByHackathonID(hackathonID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByHackathonID", reflect.TypeOf((*MockProjectRepositoryInterface)(nil).FindByHackathonID), hackathonID)
}

// FindByID mocks base method.
func (m *MockProjectRepositoryInterface) FindByID(id any) (*models.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*models.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockProjectRepositoryInterfaceMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockProjectRepositoryInterface)(nil).FindByID), id)
}

// FindByUserID mocks base method.
func (m *MockProjectRepositoryInterface) FindByUserID(userID any) (*models.Projects, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", userID)
	ret0, _ := ret[0].(*models.Projects)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockProjectRepositoryInterfaceMockRecorder) FindByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockProjectRepositoryInterface)(nil).FindByUserID), userID)
}

// FindByUserIDWithHackathon mocks base method.
func (m *MockProjectRepositoryInterface) FindByUserIDWithHackathon(userID any) (*models.Projects, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserIDWithHackathon", userID)
	ret0, _ := ret[0].(*models.Projects)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserIDWithHackathon indicates an expected call of FindByUserIDWithHackathon.
func (mr *MockProjectRepositoryInterfaceMockRecorder) FindByUserIDWithHackathon(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserIDWithHackathon", reflect.TypeOf((*MockProjectRepositoryInterface)(nil).FindByUserIDWithHackathon), userID)
}

// FindPresentingByHackathonID mocks base method.
func (m *MockProjectRepositoryInterface) FindPresentingByHackathonID(hackathonID any) (*models.Projects, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPresentingByHackathonID", hackathonID)
	ret0, _ := ret[0].(*models.Projects)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPresentingByHackathonID indicates an expected call of FindPresentingByHackathonID.
func (mr *MockProjectRepositoryInterfaceMockRecorder) FindPresentingByHackathonID(hackathonID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPresentingByHackathonID", reflect.TypeOf((*MockProjectRepositoryInterface)(nil).FindPresentingByHackathonID), hackathonID)
}

// FindPresentingFromActiveHackathons mocks base method.
func (m *MockProjectRepositoryInterface) FindPresentingFromActiveHackathons() (*models.Projects, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPresentingFromActiveHackathons")
	ret0, _ := ret[0].(*models.Projects)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPresentingFromActiveHackathons indicates an expected call of FindPresentingFromActiveHackathons.
func (mr *MockProjectRepositoryInterfaceMockRecorder) FindPresentingFromActiveHackathons() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPresentingFromActiveHackathons", reflect.TypeOf((*MockProjectRepositoryInterface)(nil).FindPresentingFromActiveHackathons))
}

// GetFilesByProjectID mocks base method.
func (m *MockProjectRepositoryInterface) GetFilesByProjectID(projectID any) (*models.Files, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilesByProjectID", projectID)
	ret0, _ := ret[0].(*models.Files)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilesByProjectID indicates an expected call of GetFilesByProjectID.
func (mr *MockProjectRepositoryInterfaceMockRecorder) GetFilesByProjectID(projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilesByProjectID", reflect.TypeOf((*MockProjectRepositoryInterface)(nil).GetFilesByProjectID), projectID)
}

// GetMembershipsByProjectID mocks base method.
func (m *MockProjectRepositoryInterface) GetMembershipsByProjectID(projectID any) (*models.ProjectMemberships, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembershipsByProjectID", projectID)
	ret0, _ := ret[0].(*models.ProjectMemberships)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembershipsByProjectID indicates an expected call of GetMembershipsByProjectID.
func (mr *MockProjectRepositoryInterfaceMockRecorder) GetMembershipsByProjectID(projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembershipsByProjectID", reflect.TypeOf((*MockProjectRepositoryInterface)(nil).GetMembershipsByProjectID), projectID)
}

// GetRecent mocks base method.
func (m *MockProjectRepositoryInterface) GetRecent(limit int) (*models.Projects, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecent", limit)
	ret0, _ := ret[0].(*models.Projects)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecent indicates an expected call of GetRecent.
func (mr *MockProjectRepositoryInterfaceMockRecorder) GetRecent(limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecent", reflect.TypeOf((*MockProjectRepositoryInterface)(nil).GetRecent), limit)
}

// IsUserMemberOfProject mocks base method.
func (m *MockProjectRepositoryInterface) IsUserMemberOfProject(projectID, userID any) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserMemberOfProject", projectID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUserMemberOfProject indicates an expected call of IsUserMemberOfProject.
func (mr *MockProjectRepositoryInterfaceMockRecorder) IsUserMemberOfProject(projectID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserMemberOfProject", reflect.TypeOf((*MockProjectRepositoryInterface)(nil).IsUserMemberOfProject), projectID, userID)
}

// MockProjectMembershipRepositoryInterface is a mock of ProjectMembershipRepositoryInterface interface.
type MockProjectMembershipRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockProjectMembershipRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockProjectMembershipRepositoryInterfaceMockRecorder is the mock recorder for MockProjectMembershipRepositoryInterface.
type MockProjectMembershipRepositoryInterfaceMockRecorder struct {
	mock *MockProjectMembershipRepositoryInterface
}

// NewMockProjectMembershipRepositoryInterface creates a new mock instance.
func NewMockProjectMembershipRepositoryInterface(ctrl *gomock.Controller) *MockProjectMembershipRepositoryInterface {
	mock := &MockProjectMembershipRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockProjectMembershipRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectMembershipRepositoryInterface) EXPECT() *MockProjectMembershipRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CountByProjectID mocks base method.
func (m *MockProjectMembershipRepositoryInterface) CountByProjectID(projectID any) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByProjectID", projectID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByProjectID indicates an expected call of CountByProjectID.
func (mr *MockProjectMembershipRepositoryInterfaceMockRecorder) CountByProjectID(projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByProjectID", reflect.TypeOf((*MockProjectMembershipRepositoryInterface)(nil).CountByProjectID), projectID)
}

// FindByProjectIDAndUserID mocks base method.
func (m *MockProjectMembershipRepositoryInterface) FindByProjectIDAndUserID(projectID, userID any) (*models.ProjectMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProjectIDAndUserID", projectID, userID)
	ret0, _ := ret[0].(*models.ProjectMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProjectIDAndUserID indicates an expected call of FindByProjectIDAndUserID.
func (mr *MockProjectMembershipRepositoryInterfaceMockRecorder) FindByProjectIDAndUserID(projectID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProjectIDAndUserID", reflect.TypeOf((*MockProjectMembershipRepositoryInterface)(nil).FindByProjectIDAndUserID), projectID, userID)
}

// IsUserMember mocks base method.
func (m *MockProjectMembershipRepositoryInterface) IsUserMember(projectID, userID any) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserMember", projectID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUserMember indicates an expected call of IsUserMember.
func (mr *MockProjectMembershipRepositoryInterfaceMockRecorder) IsUserMember(projectID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserMember", reflect.TypeOf((*MockProjectMembershipRepositoryInterface)(nil).IsUserMember), projectID, userID)
}

// MockFileRepositoryInterface is a mock of FileRepositoryInterface interface.
type MockFileRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockFileRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockFileRepositoryInterfaceMockRecorder is the mock recorder for MockFileRepositoryInterface.
type MockFileRepositoryInterfaceMockRecorder struct {
	mock *MockFileRepositoryInterface
}

// NewMockFileRepositoryInterface creates a new mock instance.
func NewMockFileRepositoryInterface(ctrl *gomock.Controller) *MockFileRepositoryInterface {
	mock := &MockFileRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockFileRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileRepositoryInterface) EXPECT() *MockFileRepositoryInterfaceMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockFileRepositoryInterface) FindAll() (*models.Files, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].(*models.Files)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockFileRepositoryInterfaceMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockFileRepositoryInterface)(nil).FindAll))
}

// FindAllHackathons mocks base method.
func (m *MockFileRepositoryInterface) FindAllHackathons() (*models.Hackathons, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllHackathons")
	ret0, _ := ret[0].(*models.Hackathons)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllHackathons indicates an expected call of FindAllHackathons.
func (mr *MockFileRepositoryInterfaceMockRecorder) FindAllHackathons() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllHackathons", reflect.TypeOf((*MockFileRepositoryInterface)(nil).FindAllHackathons))
}

// FindAllProjects mocks base method.
func (m *MockFileRepositoryInterface) FindAllProjects() (*models.Projects, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllProjects")
	ret0, _ := ret[0].(*models.Projects)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllProjects indicates an expected call of FindAllProjects.
func (mr *MockFileRepositoryInterfaceMockRecorder) FindAllProjects() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllProjects", reflect.TypeOf((*MockFileRepositoryInterface)(nil).FindAllProjects))
}

// FindByID mocks base method.
func (m *MockFileRepositoryInterface) FindByID(id any) (*models.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*models.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockFileRepositoryInterfaceMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockFileRepositoryInterface)(nil).FindByID), id)
}

// MockCompanyAllowedDomainRepositoryInterface is a mock of CompanyAllowedDomainRepositoryInterface interface.
type MockCompanyAllowedDomainRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCompanyAllowedDomainRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockCompanyAllowedDomainRepositoryInterfaceMockRecorder is the mock recorder for MockCompanyAllowedDomainRepositoryInterface.
type MockCompanyAllowedDomainRepositoryInterfaceMockRecorder struct {
	mock *MockCompanyAllowedDomainRepositoryInterface
}

// NewMockCompanyAllowedDomainRepositoryInterface creates a new mock instance.
func NewMockCompanyAllowedDomainRepositoryInterface(ctrl *gomock.Controller) *MockCompanyAllowedDomainRepositoryInterface {
	mock := &MockCompanyAllowedDomainRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockCompanyAllowedDomainRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompanyAllowedDomainRepositoryInterface) EXPECT() *MockCompanyAllowedDomainRepositoryInterfaceMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockCompanyAllowedDomainRepositoryInterface) FindAll() (*models.CompanyAllowedDomains, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].(*models.CompanyAllowedDomains)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockCompanyAllowedDomainRepositoryInterfaceMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockCompanyAllowedDomainRepositoryInterface)(nil).FindAll))
}

// FindAllActive mocks base method.
func (m *MockCompanyAllowedDomainRepositoryInterface) FindAllActive() (*models.CompanyAllowedDomains, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllActive")
	ret0, _ := ret[0].(*models.CompanyAllowedDomains)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllActive indicates an expected call of FindAllActive.
func (mr *MockCompanyAllowedDomainRepositoryInterfaceMockRecorder) FindAllActive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllActive", reflect.TypeOf((*MockCompanyAllowedDomainRepositoryInterface)(nil).FindAllActive))
}

// IsDomainAllowed mocks base method.
func (m *MockCompanyAllowedDomainRepositoryInterface) IsDomainAllowed(domain string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDomainAllowed", domain)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsDomainAllowed indicates an expected call of IsDomainAllowed.
func (mr *MockCompanyAllowedDomainRepositoryInterfaceMockRecorder) IsDomainAllowed(domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDomainAllowed", reflect.TypeOf((*MockCompanyAllowedDomainRepositoryInterface)(nil).IsDomainAllowed), domain)
}
